homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam

alarm_control_panel:
  - platform: manual
    code: !secret alarm_code
    pending_time: 30

zwave:
  usb_path: /dev/ttyACM0

#device_tracker:
#  - platform: icloud
#    username: !secret icloud_username
#    password: !secret icloud_password
#    account_name: icloud

device_tracker:
  - platform: owntracks

  - platform: nmap_tracker
    hosts:
     - 192.168.100.6
    home_interval: 10
    track_new_devices: yes
    scan_options: " --privileged -sP "

camera:
  - platform: uvc
    nvr: !secret uvc_nvr
    key: !secret uvc_apikey


# Enables the frontend
frontend:

# Enables configuration UI
config:


http:
  # Uncomment this to add a password (recommended!)
    api_password: !secret api_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
    base_url: !secret api_base_url

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:


# Text to speech

digital_ocean:
  access_token: !secret digital_ocean_access_token


sensor: !include sensors.yaml
group: !include groups.yaml
scene: !include scenes.yaml


light:
  - platform: hue
    allow_hue_groups: true
    host: !secret hue_host

# Configuration.yaml example
automation: !include automations.yaml




media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

  - platform: sonos

notify:
  - name: xmpp
    platform: xmpp
    sender: !secret xmpp_sender
    password: !secret xmpp_password
    recipient: !secret xmpp_recipient

  - name: matrix 
    platform: matrix
    homeserver: !secret matrix_homeserver
    username: !secret matrix_username
    password: !secret matrix_password
    default_room: !secret matrix_default_room


mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'
  discovery: true
  discovery_prefix: homeassistant
