default_view:
  view: true
  icon: mdi:home
  entities:
  - group.lights
  - camera.living_room
  - sun.sun
  - group.mobiledevices
  - group.automation
  - device_tracker.pi_f7288cd7c327402789335e7612a0ad60
  - group.livingroom
  - group.bedroom
  - group.bathroom
  - group.frontdoor
  name: default_view

livingroom:
  name: Living Room
  view: true
  entities:
  - camera.living_room
  - media_player.living_room
  - light.living_room_light
  - light.dining_table_light
  - light.kitchin_light
  - switch.test_switch

bedroom:
  name: Bedroom
  view: true
  entities:
  - media_player.bedroom
  - light.bedroom_bed_light
  - light.bedroom__stairs_light

bathroom:
  name: Bathroom
  view: true
  entities:
  - media_player.bathroom
  - light.wardrobe_light
  - light.bathroom_light

frontdoor:
  name: Frontdoor
  entities:
  - camera.front_door

cctv:
  name: CCTV
  view: true
  entities:
  - sun.sun
  - device_tracker.pi_f7288cd7c327402789335e7612a0ad60
  - camera.living_room
  - camera.front_door

automation:
  name: Automation
  view: false
  entities:
  - sun.sun

lights:
  name: Lights
  view: false
  entities:
  - light.bedroom
  - light.living_room
  - light.bathroom



mobiledevices:
  name: Presence
  entities:
  - device_tracker.pi_f7288cd7c327402789335e7612a0ad60
