default_view:
  view: yes
  icon: mdi:home 
  entities:
    - group.livingroom
    - group.bedroom
    - group.bathroom
    - group.frontdoor
    - group.automation

livingroom:
  name: Living Room
  entities:
    - media_player.living_room
    - light.living_room_light
    - light.dining_table_light
    - light.kitchin_light
    - switch.test_switch

bedroom:
  name: Bedroom
  entities:
    - media_player.bedroom
    - light.bedroom_bed_light
    - light.bedroom__stairs_light

bathroom:
  name: Bathroom
  entities:
    - media_player.bathroom
    - light.wardrobe_light
    - light.bathroom_light

frontdoor:
  name: Frontdoor
  entities:
    - camera.front_door

cctv:
  name: CCTV
  view: yes
  entities:
    - camera.living_room
    - camera.front_door

automation:
  name: Automation
  view: yes
